name: parkcore_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  firebase_core: ^0.4.0+9

  cloud_firestore: ^0.13.2+1
  
  # login and auth
  #firebase_auth: ^0.15.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.2.0
  #rxdart: 0.20.0
  rxdart: ^0.23.1

  google_maps_flutter: ^0.5.11
  http: ^0.12.0+1
  json_serializable: ^2.0.2

  # adds useful features for forms
  dropdown_formfield: ^0.1.1
  multiselect_formfield: ^0.1.3
  datetime_picker_formfield: ^1.0.0
  flutter_masked_text: ^0.8.0

  # for getting lat/long coordinates from address
  geocoder: ^0.2.1
  #flutter_google_places: ^0.2.4

  # for getting images from users
  image_picker: ^0.6.7
  firebase_storage: ^3.1.3
  uuid: 2.0.4
  #for Haversine Formula 
  great_circle_distance2: ^1.0.1+1

  # for SVG images
  flutter_svg: ^0.17.3+1

  #for User Ratings
  flutter_rating_bar: ^3.0.1+1

  # for Firestore unit tests
  cloud_firestore_mocks: ^0.4.5
  firebase_auth_mocks: ^0.2.1
  google_sign_in_mocks: ^0.1.0+2

dev_dependencies:
  pedantic: ^1.4.0
  build_runner: ^1.2.7
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/parkcore_logo_green.jpg
    - assets/parkcore_logo_green2.jpg
    - assets/ParkCore_WHITE_SQUIRREL_ONLY.svg
    - assets/ParkCore_WHITE_SQUIRREL.svg
    - assets/Acorns.svg
    - assets/Acorns_White.png
    - assets/text/about_us.txt
    - assets/text/about_us_short.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
